# Generated by Django 4.1.7 on 2023-03-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
